language: objective-c
osx_image: xcode7.2
git:
  submodules: false
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
script: script/cibuild | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - swiftlint
