language: objective-c
osx_image: xcode7.2
git:
  submodules: false
script: script/cibuild | xcpretty
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
after_success:
  - bash <(curl -s https://codecov.io/bash)
