#!/bin/bash

# Install Variables
INSTALL_BASE_URL='https://github.com/realm/SwiftLint'
INSTALL_TAG_NAME='master'
INSTALL_REPO_DIR='SWIFTLINT_MASTER'

# Clone source, checkout, and install.
git clone "$INSTALL_BASE_URL.git" $INSTALL_REPO_DIR
cd $INSTALL_REPO_DIR
git checkout $INSTALL_TAG_NAME
echo "Making SwiftLint baseline"
make install
cd ..
